In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
x = np.array([5, 6, 7, 8, 9, 10]).reshape((-1, 1))
y = np.array([70, 60, 50, 40, 30, 20])

In [9]:
>>> print(x)
[[5],
 [6],
 [7],
 [8],
 [9],
 [10]]
>>> print(y)
[ 70, 60, 50, 40, 30, 20]

[[ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[70 60 50 40 30 20]


[70, 60, 50, 40, 30, 20]

In [1]:
model = LinearRegression()
model.fit(x, y)

NameError: name 'LinearRegression' is not defined

In [17]:
>>> r_sq = model.score(x, y)
>>> print('coefficient of determination:', r_sq)

coefficient of determination: 1.0


In [18]:
>>> print('intercept:', model.intercept_)
intercept: 5.633333333333329
>>> print('slope:', model.coef_)

intercept: 120.00000000000001
slope: [-10.]


In [20]:
>>> new_model = LinearRegression().fit(x, y.reshape((-1, 1)))
>>> print('intercept:', new_model.intercept_)
>>> print('slope:', new_model.coef_)

intercept: [120.]
slope: [[-10.]]


In [21]:
>>> y_pred = model.predict(x)
>>> print('predicted response:', y_pred, sep='\n')

predicted response:
[70. 60. 50. 40. 30. 20.]


In [22]:
>>> y_pred = model.intercept_ + model.coef_ * x
>>> print('predicted response:', y_pred, sep='\n')

predicted response:
[[70.]
 [60.]
 [50.]
 [40.]
 [30.]
 [20.]]


In [24]:
>>> x_new = np.arange(10).reshape((-1, 1))
>>> print(x_new)
>>> y_new = model.predict(x_new)
>>> print(y_new)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[120. 110. 100.  90.  80.  70.  60.  50.  40.  30.]


In [25]:
import numpy as np
from sklearn.linear_model import LinearRegression

x = [[0, 30], [5, 32], [15, 35], [25, 37], [35, 40], [45, 45], [55, 50], [60, 65]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [26]:
>>> print(x)
>>> print(y)

[[ 0 30]
 [ 5 32]
 [15 35]
 [25 37]
 [35 40]
 [45 45]
 [55 50]
 [60 65]]
[ 4  5 20 14 32 22 38 43]


In [27]:
model = LinearRegression().fit(x, y)

In [28]:
>>> r_sq = model.score(x, y)
>>> print('coefficient of determination:', r_sq)

coefficient of determination: 0.8602538004213072


In [29]:
>>> print('intercept:', model.intercept_)

intercept: -3.2977331094429125


In [30]:
>>> print('slope:', model.coef_)

slope: [0.46573489 0.27726195]


In [31]:
>>> y_pred = model.predict(x)
>>> print('predicted response:', y_pred, sep='\n')

predicted response:
[ 5.02012544  7.90332379 13.39245851 18.60433129 24.09346602 30.13712465
 36.18078329 42.668387  ]


In [35]:
>>> x_new = np.arange(20).reshape((-2, 2))
>>> print(x_new)
>>> y_new = model.predict(x_new)
>>> print(y_new)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
[-3.02047116 -1.53447748 -0.0484838   1.43750988  2.92350356  4.40949723
  5.89549091  7.38148459  8.86747827 10.35347195]


In [36]:
>>> y_pred = model.intercept_ + np.sum(model.coef_ * x, axis=1)
>>> print('predicted response:', y_pred, sep='\n')

predicted response:
[ 5.02012544  7.90332379 13.39245851 18.60433129 24.09346602 30.13712465
 36.18078329 42.668387  ]


In [37]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [39]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([15, 11, 2, 8, 25, 32])


In [40]:
transformer = PolynomialFeatures(degree=2, include_bias=False)

In [41]:
transformer.fit(x)

PolynomialFeatures(degree=2, include_bias=False, interaction_only=False)

In [42]:
x_ = transformer.transform(x)

In [43]:
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)


In [44]:
>>> print(x_)

[[   5.   25.]
 [  15.  225.]
 [  25.  625.]
 [  35. 1225.]
 [  45. 2025.]
 [  55. 3025.]]


In [45]:
model = LinearRegression().fit(x_, y)

In [46]:
>>> r_sq = model.score(x_, y)
>>> print('coefficient of determination:', r_sq)

>>> print('intercept:', model.intercept_)

>>> print('coefficients:', model.coef_)


coefficient of determination: 0.8908516262498564
intercept: 21.372321428571425
coefficients: [-1.32357143  0.02839286]


In [47]:
x_ = PolynomialFeatures(degree=2, include_bias=True).fit_transform(x)


In [48]:
>>> print(x_)

[[1.000e+00 5.000e+00 2.500e+01]
 [1.000e+00 1.500e+01 2.250e+02]
 [1.000e+00 2.500e+01 6.250e+02]
 [1.000e+00 3.500e+01 1.225e+03]
 [1.000e+00 4.500e+01 2.025e+03]
 [1.000e+00 5.500e+01 3.025e+03]]


In [49]:
model = LinearRegression(fit_intercept=False).fit(x_, y)


In [50]:
>>> r_sq = model.score(x_, y)
>>> print('coefficient of determination:', r_sq)

>>> print('intercept:', model.intercept_)

>>> print('coefficients:', model.coef_)

coefficient of determination: 0.8908516262498565
intercept: 0.0
coefficients: [21.37232143 -1.32357143  0.02839286]


In [51]:
>>> y_pred = model.predict(x_)
>>> print('predicted response:', y_pred, sep='\n')

predicted response:
[15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]


In [52]:
# Step 1: Import packages
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

# Step 2a: Provide data
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

# Step 2b: Transform input data
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

# Step 3: Create a model and fit it
model = LinearRegression().fit(x_, y)
>>> print(x)
# Step 4: Get results
r_sq = model.score(x_, y)
intercept, coefficients = model.intercept_, model.coef_

# Step 5: Predict
y_pred = model.predict(x_)

In [53]:
>>> r_sq = model.score(x_, y)
>>> print('coefficient of determination:', r_sq)

>>> print('intercept:', model.intercept_)

>>> print('coefficients:', model.coef_)

coefficient of determination: 0.9453701449127822
intercept: 0.8430556452395734
coefficients: [ 2.44828275  0.16160353 -0.15259677  0.47928683 -0.4641851 ]


In [54]:
>>> y_pred = model.predict(x_)
>>> print('predicted response:', y_pred, sep='\n')

predicted response:
[ 0.54047408 11.36340283 16.07809622 15.79139    29.73858619 23.50834636
 39.05631386 41.92339046]


In [55]:
import numpy as np
import statsmodels.api as sm

In [56]:
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [57]:
x = sm.add_constant(x)

In [59]:
>>> print(x)
>>> print(y)

[[ 1.  0.  1.]
 [ 1.  5.  1.]
 [ 1. 15.  2.]
 [ 1. 25.  5.]
 [ 1. 35. 11.]
 [ 1. 45. 15.]
 [ 1. 55. 34.]
 [ 1. 60. 35.]]
[ 4  5 20 14 32 22 38 43]


In [60]:
model = sm.OLS(y, x)

In [61]:
results = model.fit()

In [62]:
>>> print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.862
Model:                            OLS   Adj. R-squared:                  0.806
Method:                 Least Squares   F-statistic:                     15.56
Date:                Sun, 07 Jul 2019   Prob (F-statistic):            0.00713
Time:                        18:36:31   Log-Likelihood:                -24.316
No. Observations:                   8   AIC:                             54.63
Df Residuals:                       5   BIC:                             54.87
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.5226      4.431      1.246      0.2

C:\Users\maddi\Anaconda3\lib\site-packages\scipy\stats\stats.py:1416: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  "anyway, n=%i" % int(n))


In [63]:
>>> print('coefficient of determination:', results.rsquared)

>>> print('adjusted coefficient of determination:', results.rsquared_adj)

>>> print('regression coefficients:', results.params)


coefficient of determination: 0.8615939258756777
adjusted coefficient of determination: 0.8062314962259488
regression coefficients: [5.52257928 0.44706965 0.25502548]


In [65]:
>>> print('predicted response:', results.fittedvalues, sep='\n')

>>> print('predicted response:', results.predict(x), sep='\n')



predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]
predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]
